import LayoutBase from "@layouts/LayoutBase";
import "@rainbow-me/rainbowkit/styles.css";
import "@styles/globals.css";
import { polyfill } from "interweave-ssr";
import { headers } from "next/headers";
import "react-datepicker/dist/react-datepicker.css";
import "react-loading-skeleton/dist/skeleton.css";
import "react-toastify/dist/ReactToastify.min.css";
import "react-tooltip/dist/react-tooltip.css";
import Portal from "./portal";
import Providers from "./providers";
polyfill();

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const cookie = headers().get("cookie") ?? "";

  return (
    <html lang="en">
      <body>
        <Providers cookie={cookie}>
          <LayoutBase>{children}</LayoutBase>
          <Portal />
        </Providers>
      </body>
    </html>
  );
}
