/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContestsIndexRouteImport } from './routes/contests/index'
import { Route as UserAddressRouteImport } from './routes/user/$address'
import { Route as ContestsUpcomingRouteImport } from './routes/contests/upcoming'
import { Route as ContestsPastRouteImport } from './routes/contests/past'
import { Route as ContestsLiveRouteImport } from './routes/contests/live'
import { Route as ApiTokenRouteImport } from './routes/api/token'
import { Route as UserAddressIndexRouteImport } from './routes/user/$address/index'
import { Route as ContestNewIndexRouteImport } from './routes/contest/new/index'
import { Route as UserAddressVotesRouteImport } from './routes/user/$address/votes'
import { Route as UserAddressSubmissionsRouteImport } from './routes/user/$address/submissions'
import { Route as UserAddressCommentsRouteImport } from './routes/user/$address/comments'
import { Route as ApiTweetIdRouteImport } from './routes/api/tweet/$id'
import { Route as ContestChainAddressIndexRouteImport } from './routes/contest/$chain/$address/index'
import { Route as ContestChainAddressSubmissionSubmissionIndexRouteImport } from './routes/contest/$chain/$address/submission/$submission/index'

const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsIndexRoute = ContestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContestsRoute,
} as any)
const UserAddressRoute = UserAddressRouteImport.update({
  id: '/user/$address',
  path: '/user/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsUpcomingRoute = ContestsUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => ContestsRoute,
} as any)
const ContestsPastRoute = ContestsPastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => ContestsRoute,
} as any)
const ContestsLiveRoute = ContestsLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ContestsRoute,
} as any)
const ApiTokenRoute = ApiTokenRouteImport.update({
  id: '/api/token',
  path: '/api/token',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAddressIndexRoute = UserAddressIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserAddressRoute,
} as any)
const ContestNewIndexRoute = ContestNewIndexRouteImport.update({
  id: '/contest/new/',
  path: '/contest/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAddressVotesRoute = UserAddressVotesRouteImport.update({
  id: '/votes',
  path: '/votes',
  getParentRoute: () => UserAddressRoute,
} as any)
const UserAddressSubmissionsRoute = UserAddressSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => UserAddressRoute,
} as any)
const UserAddressCommentsRoute = UserAddressCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => UserAddressRoute,
} as any)
const ApiTweetIdRoute = ApiTweetIdRouteImport.update({
  id: '/api/tweet/$id',
  path: '/api/tweet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestChainAddressIndexRoute =
  ContestChainAddressIndexRouteImport.update({
    id: '/contest/$chain/$address/',
    path: '/contest/$chain/$address/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContestChainAddressSubmissionSubmissionIndexRoute =
  ContestChainAddressSubmissionSubmissionIndexRouteImport.update({
    id: '/contest/$chain/$address/submission/$submission/',
    path: '/contest/$chain/$address/submission/$submission/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contests': typeof ContestsRouteWithChildren
  '/api/token': typeof ApiTokenRoute
  '/contests/live': typeof ContestsLiveRoute
  '/contests/past': typeof ContestsPastRoute
  '/contests/upcoming': typeof ContestsUpcomingRoute
  '/user/$address': typeof UserAddressRouteWithChildren
  '/contests/': typeof ContestsIndexRoute
  '/api/tweet/$id': typeof ApiTweetIdRoute
  '/user/$address/comments': typeof UserAddressCommentsRoute
  '/user/$address/submissions': typeof UserAddressSubmissionsRoute
  '/user/$address/votes': typeof UserAddressVotesRoute
  '/contest/new': typeof ContestNewIndexRoute
  '/user/$address/': typeof UserAddressIndexRoute
  '/contest/$chain/$address': typeof ContestChainAddressIndexRoute
  '/contest/$chain/$address/submission/$submission': typeof ContestChainAddressSubmissionSubmissionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/token': typeof ApiTokenRoute
  '/contests/live': typeof ContestsLiveRoute
  '/contests/past': typeof ContestsPastRoute
  '/contests/upcoming': typeof ContestsUpcomingRoute
  '/contests': typeof ContestsIndexRoute
  '/api/tweet/$id': typeof ApiTweetIdRoute
  '/user/$address/comments': typeof UserAddressCommentsRoute
  '/user/$address/submissions': typeof UserAddressSubmissionsRoute
  '/user/$address/votes': typeof UserAddressVotesRoute
  '/contest/new': typeof ContestNewIndexRoute
  '/user/$address': typeof UserAddressIndexRoute
  '/contest/$chain/$address': typeof ContestChainAddressIndexRoute
  '/contest/$chain/$address/submission/$submission': typeof ContestChainAddressSubmissionSubmissionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contests': typeof ContestsRouteWithChildren
  '/api/token': typeof ApiTokenRoute
  '/contests/live': typeof ContestsLiveRoute
  '/contests/past': typeof ContestsPastRoute
  '/contests/upcoming': typeof ContestsUpcomingRoute
  '/user/$address': typeof UserAddressRouteWithChildren
  '/contests/': typeof ContestsIndexRoute
  '/api/tweet/$id': typeof ApiTweetIdRoute
  '/user/$address/comments': typeof UserAddressCommentsRoute
  '/user/$address/submissions': typeof UserAddressSubmissionsRoute
  '/user/$address/votes': typeof UserAddressVotesRoute
  '/contest/new/': typeof ContestNewIndexRoute
  '/user/$address/': typeof UserAddressIndexRoute
  '/contest/$chain/$address/': typeof ContestChainAddressIndexRoute
  '/contest/$chain/$address/submission/$submission/': typeof ContestChainAddressSubmissionSubmissionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contests'
    | '/api/token'
    | '/contests/live'
    | '/contests/past'
    | '/contests/upcoming'
    | '/user/$address'
    | '/contests/'
    | '/api/tweet/$id'
    | '/user/$address/comments'
    | '/user/$address/submissions'
    | '/user/$address/votes'
    | '/contest/new'
    | '/user/$address/'
    | '/contest/$chain/$address'
    | '/contest/$chain/$address/submission/$submission'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/token'
    | '/contests/live'
    | '/contests/past'
    | '/contests/upcoming'
    | '/contests'
    | '/api/tweet/$id'
    | '/user/$address/comments'
    | '/user/$address/submissions'
    | '/user/$address/votes'
    | '/contest/new'
    | '/user/$address'
    | '/contest/$chain/$address'
    | '/contest/$chain/$address/submission/$submission'
  id:
    | '__root__'
    | '/'
    | '/contests'
    | '/api/token'
    | '/contests/live'
    | '/contests/past'
    | '/contests/upcoming'
    | '/user/$address'
    | '/contests/'
    | '/api/tweet/$id'
    | '/user/$address/comments'
    | '/user/$address/submissions'
    | '/user/$address/votes'
    | '/contest/new/'
    | '/user/$address/'
    | '/contest/$chain/$address/'
    | '/contest/$chain/$address/submission/$submission/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContestsRoute: typeof ContestsRouteWithChildren
  ApiTokenRoute: typeof ApiTokenRoute
  UserAddressRoute: typeof UserAddressRouteWithChildren
  ApiTweetIdRoute: typeof ApiTweetIdRoute
  ContestNewIndexRoute: typeof ContestNewIndexRoute
  ContestChainAddressIndexRoute: typeof ContestChainAddressIndexRoute
  ContestChainAddressSubmissionSubmissionIndexRoute: typeof ContestChainAddressSubmissionSubmissionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests/': {
      id: '/contests/'
      path: '/'
      fullPath: '/contests/'
      preLoaderRoute: typeof ContestsIndexRouteImport
      parentRoute: typeof ContestsRoute
    }
    '/user/$address': {
      id: '/user/$address'
      path: '/user/$address'
      fullPath: '/user/$address'
      preLoaderRoute: typeof UserAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests/upcoming': {
      id: '/contests/upcoming'
      path: '/upcoming'
      fullPath: '/contests/upcoming'
      preLoaderRoute: typeof ContestsUpcomingRouteImport
      parentRoute: typeof ContestsRoute
    }
    '/contests/past': {
      id: '/contests/past'
      path: '/past'
      fullPath: '/contests/past'
      preLoaderRoute: typeof ContestsPastRouteImport
      parentRoute: typeof ContestsRoute
    }
    '/contests/live': {
      id: '/contests/live'
      path: '/live'
      fullPath: '/contests/live'
      preLoaderRoute: typeof ContestsLiveRouteImport
      parentRoute: typeof ContestsRoute
    }
    '/api/token': {
      id: '/api/token'
      path: '/api/token'
      fullPath: '/api/token'
      preLoaderRoute: typeof ApiTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$address/': {
      id: '/user/$address/'
      path: '/'
      fullPath: '/user/$address/'
      preLoaderRoute: typeof UserAddressIndexRouteImport
      parentRoute: typeof UserAddressRoute
    }
    '/contest/new/': {
      id: '/contest/new/'
      path: '/contest/new'
      fullPath: '/contest/new'
      preLoaderRoute: typeof ContestNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$address/votes': {
      id: '/user/$address/votes'
      path: '/votes'
      fullPath: '/user/$address/votes'
      preLoaderRoute: typeof UserAddressVotesRouteImport
      parentRoute: typeof UserAddressRoute
    }
    '/user/$address/submissions': {
      id: '/user/$address/submissions'
      path: '/submissions'
      fullPath: '/user/$address/submissions'
      preLoaderRoute: typeof UserAddressSubmissionsRouteImport
      parentRoute: typeof UserAddressRoute
    }
    '/user/$address/comments': {
      id: '/user/$address/comments'
      path: '/comments'
      fullPath: '/user/$address/comments'
      preLoaderRoute: typeof UserAddressCommentsRouteImport
      parentRoute: typeof UserAddressRoute
    }
    '/api/tweet/$id': {
      id: '/api/tweet/$id'
      path: '/api/tweet/$id'
      fullPath: '/api/tweet/$id'
      preLoaderRoute: typeof ApiTweetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest/$chain/$address/': {
      id: '/contest/$chain/$address/'
      path: '/contest/$chain/$address'
      fullPath: '/contest/$chain/$address'
      preLoaderRoute: typeof ContestChainAddressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest/$chain/$address/submission/$submission/': {
      id: '/contest/$chain/$address/submission/$submission/'
      path: '/contest/$chain/$address/submission/$submission'
      fullPath: '/contest/$chain/$address/submission/$submission'
      preLoaderRoute: typeof ContestChainAddressSubmissionSubmissionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContestsRouteChildren {
  ContestsLiveRoute: typeof ContestsLiveRoute
  ContestsPastRoute: typeof ContestsPastRoute
  ContestsUpcomingRoute: typeof ContestsUpcomingRoute
  ContestsIndexRoute: typeof ContestsIndexRoute
}

const ContestsRouteChildren: ContestsRouteChildren = {
  ContestsLiveRoute: ContestsLiveRoute,
  ContestsPastRoute: ContestsPastRoute,
  ContestsUpcomingRoute: ContestsUpcomingRoute,
  ContestsIndexRoute: ContestsIndexRoute,
}

const ContestsRouteWithChildren = ContestsRoute._addFileChildren(
  ContestsRouteChildren,
)

interface UserAddressRouteChildren {
  UserAddressCommentsRoute: typeof UserAddressCommentsRoute
  UserAddressSubmissionsRoute: typeof UserAddressSubmissionsRoute
  UserAddressVotesRoute: typeof UserAddressVotesRoute
  UserAddressIndexRoute: typeof UserAddressIndexRoute
}

const UserAddressRouteChildren: UserAddressRouteChildren = {
  UserAddressCommentsRoute: UserAddressCommentsRoute,
  UserAddressSubmissionsRoute: UserAddressSubmissionsRoute,
  UserAddressVotesRoute: UserAddressVotesRoute,
  UserAddressIndexRoute: UserAddressIndexRoute,
}

const UserAddressRouteWithChildren = UserAddressRoute._addFileChildren(
  UserAddressRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContestsRoute: ContestsRouteWithChildren,
  ApiTokenRoute: ApiTokenRoute,
  UserAddressRoute: UserAddressRouteWithChildren,
  ApiTweetIdRoute: ApiTweetIdRoute,
  ContestNewIndexRoute: ContestNewIndexRoute,
  ContestChainAddressIndexRoute: ContestChainAddressIndexRoute,
  ContestChainAddressSubmissionSubmissionIndexRoute:
    ContestChainAddressSubmissionSubmissionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
