name: nextjs-docker

on: 
  push:
    branches:
      - main

permissions:
  packages: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-upload-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: |
            ghcr.io/jk-labs-inc/jokerace:main
            registry.digitalocean.com/jk-labs-inc/jokerace:main
          outputs: type=docker,dest=/tmp/nextjs_docker_image.tar
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.PROD_NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.PROD_NEXT_PUBLIC_SUPABASE_ANON_KEY }}
            NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${{ secrets.PROD_NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID }}
            NEXT_PUBLIC_R2_ACCOUNT_ID=${{ secrets.PROD_NEXT_PUBLIC_R2_ACCOUNT_ID }}
            NEXT_PUBLIC_R2_ACCESS_KEY_ID=${{ secrets.PROD_NEXT_PUBLIC_R2_ACCESS_KEY_ID }}
            NEXT_PUBLIC_R2_SECRET_ACCESS_KEY=${{ secrets.PROD_NEXT_PUBLIC_R2_SECRET_ACCESS_KEY }}
            NEXT_PUBLIC_IMAGE_UPLOAD_BUCKET=${{ secrets.PROD_NEXT_PUBLIC_IMAGE_UPLOAD_BUCKET }}
            NEXT_PUBLIC_QUICKNODE_SLUG=${{ secrets.PROD_NEXT_PUBLIC_QUICKNODE_SLUG }}
            NEXT_PUBLIC_QUICKNODE_KEY=${{ secrets.PROD_NEXT_PUBLIC_QUICKNODE_KEY }}
            NEXT_PUBLIC_ALCHEMY_KEY=${{ secrets.PROD_NEXT_PUBLIC_ALCHEMY_KEY }}
            NEXT_PUBLIC_PARA_API_KEY=${{ secrets.PROD_NEXT_PUBLIC_PARA_API_KEY }}
            NEXT_PUBLIC_PARA_ENVIRONMENT=${{ secrets.PROD_NEXT_PUBLIC_PARA_ENVIRONMENT }}
            NEXT_PUBLIC_BREVO_API_KEY=${{ secrets.PROD_NEXT_PUBLIC_BREVO_API_KEY }}
            NEXT_PUBLIC_ENVIRONMENT=${{ secrets.PROD_NEXT_PUBLIC_ENVIRONMENT }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs_docker_image
          path: /tmp/nextjs_docker_image.tar

  github-push:
    needs: build-and-upload-image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs_docker_image
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/nextjs_docker_image.tar
          docker image ls -a

      - name: Push image to Github Container Registry
        run: docker push ghcr.io/jk-labs-inc/jokerace:main
